//! PhiCade core-neutral runtime.
//!
//! This crate intentionally does not embed emulator cores. It defines the trust
//! boundary that future core adapters must satisfy.

pub mod action_bus;
pub mod authority;
pub mod agent_gym;
pub mod autodrive;
pub mod benchmark_campaign;
pub mod campaign_comparison;
pub mod suite_report;
pub mod suite_comparison;
pub mod core;
pub mod driver;
pub mod library;
pub mod replay;
pub mod observation;

pub use action_bus::{
    live_source_order, ActionBus, ActionEnvelope, ActionKind, ActionSource, SystemCommand,
};
pub use authority::{AgentGrant, AuthorityDecision, AuthorityPolicy, ControlMode};
pub use agent_gym::{
    agent_gym_distance, agent_gym_score_1000, agent_gym_success, benchmark_suite_by_id,
    benchmark_suite_v1_tasks, benchmark_suite_v2_tasks, benchmark_suite_v3_tasks, benchmark_suite_v4_tasks, benchmark_suite_v5_tasks, benchmark_suite_v6_tasks, benchmark_suite_v7_tasks, benchmark_suite_v8_tasks, benchmark_suite_v9_tasks, benchmark_suite_v10_tasks, benchmark_suites,
    benchmark_suites_for_task, benchmark_task_by_id, benchmark_task_by_rom_sha256,
    benchmark_task_distance, benchmark_task_success, locate_agent_gym_player,
    score_agent_gym_frame, score_benchmark_task_frame, AgentGymScore, BenchmarkSuiteSpec,
    BenchmarkTaskSpec, OracleLeg, PixelPoint, AGENT_GYM_ID, AGENT_GYM_INITIAL_DISTANCE,
    AGENT_GYM_MIRROR_ID, AGENT_GYM_MIRROR_ROM_SHA256, AGENT_GYM_MIRROR_SOURCE_SHA256,
    AGENT_GYM_MIRROR_START, AGENT_GYM_MIRROR_TARGET, AGENT_GYM_MIRROR_TASK,
    AGENT_GYM_ROM_SHA256, AGENT_GYM_SOURCE_SHA256, AGENT_GYM_START,
    AGENT_GYM_SUCCESS_DISTANCE, AGENT_GYM_TARGET, AGENT_GYM_TASK,
    AGENT_GYM_WALL_ID, AGENT_GYM_WALL_INITIAL_DISTANCE, AGENT_GYM_WALL_ROM_SHA256,
    AGENT_GYM_WALL_SOURCE_SHA256, AGENT_GYM_WALL_START, AGENT_GYM_WALL_TARGET,
    AGENT_GYM_WALL_TASK, AGENT_GYM_WARMUP_FRAMES,
    AGENT_GYM_TEMPORAL_LEFT_ID, AGENT_GYM_TEMPORAL_LEFT_ORACLE,
    AGENT_GYM_TEMPORAL_LEFT_ROM_SHA256, AGENT_GYM_TEMPORAL_LEFT_SOURCE_SHA256,
    AGENT_GYM_TEMPORAL_LEFT_TARGET, AGENT_GYM_TEMPORAL_LEFT_TASK,
    AGENT_GYM_TEMPORAL_RIGHT_ID, AGENT_GYM_TEMPORAL_RIGHT_ORACLE,
    AGENT_GYM_TEMPORAL_RIGHT_ROM_SHA256, AGENT_GYM_TEMPORAL_RIGHT_SOURCE_SHA256,
    AGENT_GYM_TEMPORAL_RIGHT_TARGET, AGENT_GYM_TEMPORAL_RIGHT_TASK,
    AGENT_GYM_TEMPORAL_START, AGENT_GYM_TEMPORAL_INITIAL_DISTANCE,
    AGENT_GYM_RELAY_LEFT_ID, AGENT_GYM_RELAY_LEFT_ORACLE,
    AGENT_GYM_RELAY_LEFT_ROM_SHA256, AGENT_GYM_RELAY_LEFT_SOURCE_SHA256,
    AGENT_GYM_RELAY_LEFT_TARGET, AGENT_GYM_RELAY_LEFT_TASK,
    AGENT_GYM_RELAY_RIGHT_ID, AGENT_GYM_RELAY_RIGHT_ORACLE,
    AGENT_GYM_RELAY_RIGHT_ROM_SHA256, AGENT_GYM_RELAY_RIGHT_SOURCE_SHA256,
    AGENT_GYM_RELAY_RIGHT_TARGET, AGENT_GYM_RELAY_RIGHT_TASK,
    AGENT_GYM_RELAY_START, AGENT_GYM_RELAY_INITIAL_DISTANCE,
    AGENT_GYM_KEY_GATE_LEFT_ID, AGENT_GYM_KEY_GATE_LEFT_ORACLE,
    AGENT_GYM_KEY_GATE_LEFT_ROM_SHA256, AGENT_GYM_KEY_GATE_LEFT_SOURCE_SHA256,
    AGENT_GYM_KEY_GATE_LEFT_TASK, AGENT_GYM_KEY_GATE_RIGHT_ID,
    AGENT_GYM_KEY_GATE_RIGHT_ORACLE, AGENT_GYM_KEY_GATE_RIGHT_ROM_SHA256,
    AGENT_GYM_KEY_GATE_RIGHT_SOURCE_SHA256, AGENT_GYM_KEY_GATE_RIGHT_TASK,
    AGENT_GYM_KEY_GATE_START, AGENT_GYM_KEY_GATE_TARGET,
    AGENT_GYM_KEY_GATE_INITIAL_DISTANCE,
    AGENT_GYM_POWER_CHAIN_LEFT_ID, AGENT_GYM_POWER_CHAIN_LEFT_ORACLE,
    AGENT_GYM_POWER_CHAIN_LEFT_ROM_SHA256, AGENT_GYM_POWER_CHAIN_LEFT_SOURCE_SHA256,
    AGENT_GYM_POWER_CHAIN_LEFT_TASK, AGENT_GYM_POWER_CHAIN_RIGHT_ID,
    AGENT_GYM_POWER_CHAIN_RIGHT_ORACLE, AGENT_GYM_POWER_CHAIN_RIGHT_ROM_SHA256,
    AGENT_GYM_POWER_CHAIN_RIGHT_SOURCE_SHA256, AGENT_GYM_POWER_CHAIN_RIGHT_TASK,
    AGENT_GYM_POWER_CHAIN_START, AGENT_GYM_POWER_CHAIN_TARGET,
    AGENT_GYM_POWER_CHAIN_INITIAL_DISTANCE,
    AGENT_GYM_BRANCH_SELECTOR_TRIANGLE_ID, AGENT_GYM_BRANCH_SELECTOR_TRIANGLE_ORACLE,
    AGENT_GYM_BRANCH_SELECTOR_TRIANGLE_ROM_SHA256,
    AGENT_GYM_BRANCH_SELECTOR_TRIANGLE_SOURCE_SHA256,
    AGENT_GYM_BRANCH_SELECTOR_TRIANGLE_TASK, AGENT_GYM_BRANCH_SELECTOR_SQUARE_ID,
    AGENT_GYM_BRANCH_SELECTOR_SQUARE_ORACLE, AGENT_GYM_BRANCH_SELECTOR_SQUARE_ROM_SHA256,
    AGENT_GYM_BRANCH_SELECTOR_SQUARE_SOURCE_SHA256, AGENT_GYM_BRANCH_SELECTOR_SQUARE_TASK,
    AGENT_GYM_BRANCH_SELECTOR_START, AGENT_GYM_BRANCH_SELECTOR_TARGET,
    AGENT_GYM_BRANCH_SELECTOR_INITIAL_DISTANCE,
    AGENT_GYM_NESTED_TRIANGLE_CIRCLE_ID, AGENT_GYM_NESTED_TRIANGLE_CIRCLE_ORACLE,
    AGENT_GYM_NESTED_TRIANGLE_CIRCLE_ROM_SHA256, AGENT_GYM_NESTED_TRIANGLE_CIRCLE_SOURCE_SHA256,
    AGENT_GYM_NESTED_TRIANGLE_CIRCLE_TASK, AGENT_GYM_NESTED_TRIANGLE_CROSS_ID,
    AGENT_GYM_NESTED_TRIANGLE_CROSS_ORACLE, AGENT_GYM_NESTED_TRIANGLE_CROSS_ROM_SHA256,
    AGENT_GYM_NESTED_TRIANGLE_CROSS_SOURCE_SHA256, AGENT_GYM_NESTED_TRIANGLE_CROSS_TASK,
    AGENT_GYM_NESTED_SQUARE_CIRCLE_ID, AGENT_GYM_NESTED_SQUARE_CIRCLE_ORACLE,
    AGENT_GYM_NESTED_SQUARE_CIRCLE_ROM_SHA256, AGENT_GYM_NESTED_SQUARE_CIRCLE_SOURCE_SHA256,
    AGENT_GYM_NESTED_SQUARE_CIRCLE_TASK, AGENT_GYM_NESTED_SQUARE_CROSS_ID,
    AGENT_GYM_NESTED_SQUARE_CROSS_ORACLE, AGENT_GYM_NESTED_SQUARE_CROSS_ROM_SHA256,
    AGENT_GYM_NESTED_SQUARE_CROSS_SOURCE_SHA256, AGENT_GYM_NESTED_SQUARE_CROSS_TASK,
    AGENT_GYM_NESTED_START, AGENT_GYM_NESTED_TARGET, AGENT_GYM_NESTED_INITIAL_DISTANCE,
    AGENT_GYM_BINDING_NORMAL_TRIANGLE_ID, AGENT_GYM_BINDING_NORMAL_TRIANGLE_ROM_SHA256,
    AGENT_GYM_BINDING_NORMAL_TRIANGLE_SOURCE_SHA256, AGENT_GYM_BINDING_NORMAL_TRIANGLE_TASK,
    AGENT_GYM_BINDING_NORMAL_SQUARE_ID, AGENT_GYM_BINDING_NORMAL_SQUARE_ROM_SHA256,
    AGENT_GYM_BINDING_NORMAL_SQUARE_SOURCE_SHA256, AGENT_GYM_BINDING_NORMAL_SQUARE_TASK,
    AGENT_GYM_BINDING_SWAPPED_TRIANGLE_ID, AGENT_GYM_BINDING_SWAPPED_TRIANGLE_ROM_SHA256,
    AGENT_GYM_BINDING_SWAPPED_TRIANGLE_SOURCE_SHA256, AGENT_GYM_BINDING_SWAPPED_TRIANGLE_TASK,
    AGENT_GYM_BINDING_SWAPPED_SQUARE_ID, AGENT_GYM_BINDING_SWAPPED_SQUARE_ROM_SHA256,
    AGENT_GYM_BINDING_SWAPPED_SQUARE_SOURCE_SHA256, AGENT_GYM_BINDING_SWAPPED_SQUARE_TASK,
    AGENT_GYM_BINDING_LEFT_ORACLE, AGENT_GYM_BINDING_RIGHT_ORACLE, AGENT_GYM_BINDING_START,
    AGENT_GYM_BINDING_LEFT_TARGET, AGENT_GYM_BINDING_RIGHT_TARGET, AGENT_GYM_BINDING_INITIAL_DISTANCE,
    AGENT_GYM_COMP_NTM_ID, AGENT_GYM_COMP_NTM_ROM_SHA256, AGENT_GYM_COMP_NTM_SOURCE_SHA256, AGENT_GYM_COMP_NTM_TASK,
    AGENT_GYM_COMP_NTF_ID, AGENT_GYM_COMP_NTF_ROM_SHA256, AGENT_GYM_COMP_NTF_SOURCE_SHA256, AGENT_GYM_COMP_NTF_TASK,
    AGENT_GYM_COMP_NSM_ID, AGENT_GYM_COMP_NSM_ROM_SHA256, AGENT_GYM_COMP_NSM_SOURCE_SHA256, AGENT_GYM_COMP_NSM_TASK,
    AGENT_GYM_COMP_NSF_ID, AGENT_GYM_COMP_NSF_ROM_SHA256, AGENT_GYM_COMP_NSF_SOURCE_SHA256, AGENT_GYM_COMP_NSF_TASK,
    AGENT_GYM_COMP_STM_ID, AGENT_GYM_COMP_STM_ROM_SHA256, AGENT_GYM_COMP_STM_SOURCE_SHA256, AGENT_GYM_COMP_STM_TASK,
    AGENT_GYM_COMP_STF_ID, AGENT_GYM_COMP_STF_ROM_SHA256, AGENT_GYM_COMP_STF_SOURCE_SHA256, AGENT_GYM_COMP_STF_TASK,
    AGENT_GYM_COMP_SSM_ID, AGENT_GYM_COMP_SSM_ROM_SHA256, AGENT_GYM_COMP_SSM_SOURCE_SHA256, AGENT_GYM_COMP_SSM_TASK,
    AGENT_GYM_COMP_SSF_ID, AGENT_GYM_COMP_SSF_ROM_SHA256, AGENT_GYM_COMP_SSF_SOURCE_SHA256, AGENT_GYM_COMP_SSF_TASK,
    AGENT_GYM_COMPOSITIONAL_BUTTONS,
    BENCHMARK_SUITE_V1_ID, BENCHMARK_SUITE_V2_ID, BENCHMARK_SUITE_V3_ID,
    BENCHMARK_SUITE_V4_ID, BENCHMARK_SUITE_V5_ID, BENCHMARK_SUITE_V6_ID,
    BENCHMARK_SUITE_V7_ID, BENCHMARK_SUITE_V8_ID, BENCHMARK_SUITE_V9_ID, BENCHMARK_SUITE_V10_ID, BENCHMARK_TASKS,
};
pub use autodrive::{
    AutodrivePolicy, AutodriveReceipt, AutodriveStatus, AutodriveStopReason,
    AUTODRIVE_RECEIPT_SCHEMA, AUTODRIVE_STATUS_SCHEMA,
};
pub use benchmark_campaign::{
    summarize_benchmark_trials, BenchmarkCampaignStats, BenchmarkTrialOutcome,
    BENCHMARK_CAMPAIGN_SCHEMA,
};
pub use campaign_comparison::{
    compare_campaign_samples, CampaignComparisonStats, CampaignSampleSummary,
    CAMPAIGN_COMPARISON_SCHEMA,
};
pub use suite_report::{
    summarize_benchmark_suite, BenchmarkSuiteAggregateStats, SuiteTaskAggregateInput,
    BENCHMARK_SUITE_REPORT_SCHEMA,
};
pub use suite_comparison::{
    compare_benchmark_suites, BenchmarkSuiteComparisonStats, SuiteTaskComparisonDelta,
    SuiteTaskComparisonInput, BENCHMARK_SUITE_COMPARISON_SCHEMA,
};
pub use core::{AudioBuffer, CoreError, EmulatorCore, FrameBuffer};
pub use driver::{
    compile_agent_turn, AgentTurnAction, AgentTurnRequest, AgentTurnResponse,
    AGENT_MEMORY_MAX_BYTES, AGENT_TURN_REQUEST_SCHEMA, AGENT_TURN_RESPONSE_SCHEMA,
};
pub use library::{GameImage, SystemId};
pub use replay::{
    ReplayCheckpoint, ReplayLedger, ReplayReceipt, ReplayVerification,
    ReplayVerificationResult, REPLAY_RECEIPT_SCHEMA, REPLAY_SCHEMA,
};

pub use observation::{PhiBotObservation, PHIBOT_OBSERVATION_SCHEMA};
